CREATE DATABASE SYSFUNCTIONS

USE SYSFUNCTIONS

CREATE TABLE EMP(ENUM INT,ENAME VARCHAR(20),JOB VARCHAR(20),
HIREDATE DATE,ESALARY INT,DNO INT)

INSERT INTO EMP VALUES(101,'Sunil','TRAINE','2020-02-12',50000,10)
INSERT INTO EMP VALUES(102,'SRI','DEV','2020-02-11',-20000,10)
INSERT INTO EMP VALUES(103,'SHEWAG','PRESIDENT','2005-02-01',60000,10)
INSERT INTO EMP VALUES(104,'KOHLI','DEV','2020-03-12',40000,10)
INSERT INTO EMP VALUES(105,'Warner','SALESMAN','2021-02-10',25000,20)
INSERT INTO EMP VALUES(106,'SMITH','CLERK','2021-10-02',-25000,20)
INSERT INTO EMP VALUES(107,'Venky','ANALYST','2021-02-12',30000,20)
INSERT INTO EMP VALUES(108,'STARC','SALESMAN','2021-02-13',-25000,20)
INSERT INTO EMP VALUES(109,'Finch','CLERK','2021-02-15',12000,30)
INSERT INTO EMP VALUES(110,'PANDYA','ANALYST','2000-02-16',25000,30)
INSERT INTO EMP VALUES(111,'Maxwell','CLERK','2000-02-19',-10000,30)


SELECT * FROM EMP

				-- SINGLE ROW FUNCTIONS

-- THESE FUNCTIONS EXCUITED ON ROW-BY-ROW
-- THESE FUNCTIONS RETURNS SINGLE VALUE FOR SINGLE ROW

					-- CHAR OR STRING

-- THESE FUNCTIONS EXCUITED ON STRING COLUMN OR CHAR COLUMN

-- LEN()
	SELECT ENAME,LEN(ENAME) FROM EMP	--TO GET LENGHT OF THE STRING

-- LOWER()
	SELECT ENAME,LOWER(ENAME) FROM EMP	-- TO CONVERT THE STRING TO LOWER CASE

-- UPPER()
	SELECT ENAME,UPPER(ENAME) FROM EMP	-- TO CONVERT THE STRING TO UPPER CASE

-- SUBSTRING()
	SELECT ENAME,SUBSTRING(ENAME,2,3) FROM EMP

-- CHAR INDEX
	SELECT ENAME,CHARINDEX('H',ENAME) FROM EMP	-- IT GIVES THE POSITION OF THE CHAR

-- REVERSE()
	SELECT ENAME,REVERSE(ENAME) FROM EMP	-- IT WILL REVERSE THE STRING

-- REPLICATE()
	SELECT ENAME,REPLICATE(ENAME,3) FROM EMP	-- TO REPEATE THE STRING

-- LEFT()
	SELECT ENAME,LEFT(ENAME,3) FROM EMP	-- TO GET THE NO.OF CHARCTERS FROM LEFT SIDE OF THE COLUMN

-- RIGHT()
	SELECT ENAME,RIGHT(ENAME,3) FROM EMP	-- TO GET THE NO.OF CHARCTERS FROM RIGHT SIDE OF THE COLUMN

-- CONCATENATE
	SELECT ENAME + JOB FROM EMP
	SELECT ENAME +' - ' + JOB FROM EMP	-- TO COMBINE THE TWO STRING COLUMNS INTO SINGLE COLUMN

					-- NUMBER OR MATHEMATICAL

-- THESE FUNCTIONS EXCUITED ON NUMBER COLUMN

-- ABS()
	SELECT ABS(-10)	-- IT DOESN'T CONSIDER THE SIGN OF A VALUE
	SELECT ABS(ESALARY) FROM EMP

-- SIGN()
	SELECT SIGN(-20)	-- IT WILL SELECT ONLY THE SIGN OF THE VALUE
	SELECT SIGN(ESALARY) FROM EMP

-- CEILING()
	SELECT CEILING(34.2)	-- REMOVES THE DECIMAL VAUES AND PROMOTED TO NEXT NUMBER
	SELECT CEILING(-34.2)	-- REMOVES THE DECIMAL VALUES AND GIVES THE SAME NUMBER

--FLOOR()
	SELECT FLOOR(34.9)	-- IT IS USED TO GET FLOOR DOWN TO INTEGER VALUE
	SELECT FLOOR(-34.9)

-- ROUND()
	SELECT ROUND(23.3456,1)	-- IT WILL TAKE ONLY FIRST DECIMAL PLACE
	SELECT ROUND(23.3456,2) -- IT WILL TAKE FIRST TWO DECIMAL PLACE

-- SQRT()
	SELECT SQRT(64)	-- TO GET THE SQRT OF THE NUMBER

-- POWER()
	SELECT POWER(2,4)	-- TO GET THE POWER OF THE NUMBER

-- LOG()
	SELECT LOG10(2)

-- EXP
	SELECT EXP(2)	-- TO GET THE EXPONENTIAL VALUE (e2)

						-- DATE AND TIME

-- THESE FUNCTIONS ARE EXCUITED ON DATE COLUMN OR TIME COLUMN

-- GETDATE
	SELECT GETDATE()	-- TO GET SYSTEM DATE AND TIME

-- DAY()
	SELECT DAY(GETDATE())	-- TO GET THE DAY OF THE DATE
	
-- MONTH()
	SELECT MONTH(GETDATE())	-- TO GET THE MONTH NUMBER

-- YEAR()
	SELECT YEAR(GETDATE())	-- TO GET THE YEAR NUMBER

-- DATEPART()	-- IT IS USED TO GET DATE PARTITION VALUE BASED ON THE INTERVAL 
	SELECT DATEPART(DW,GETDATE())	-- IT WILL GET THE DAY NUMBER IN A WEEK
	
/*		INTERVALS -->	DD  -->DATE NUMBER
						DW  -->WEEK OF DAY
						DY  -->DAY OF YEAR
						WW  -->WEEK OF YEAR
						QQ	-->QUARTER OF THE YEAR
						YY  -->YEAR VALUE LAST TWO DIGITS
						YYY -->YEAR VALUE LAST 3 DIGITS
						YYYY -->YEAR VALUE LAST 4 DIGITS
						MM  -->MONTH
						HH  -->HOURS
						MI  -->MINUTES
						SS  -->SECONDS
						MS  -->MILLI SECOND */
					
SELECT ENAME,HIREDATE,YEAR(HIREDATE) AS YEARNUM FROM EMP -- TO GET THE YEAR
SELECT ENAME,HIREDATE,MONTH(HIREDATE) AS MONTHNUM FROM EMP -- TO GET THE MONTH
SELECT ENAME,HIREDATE,DAY(HIREDATE) AS DAYNUM FROM EMP -- TO GET THE DAY

-- DATENAME()
	SELECT DATENAME(MM,GETDATE())
	SELECT ENAME,HIREDATE,DATENAME(YYYY,HIREDATE) FROM Emp
	SELECT ENAME,HIREDATE,DATENAME(MM,HIREDATE) FROM Emp
	SELECT ENAME,HIREDATE,DATENAME(DW,HIREDATE) FROM Emp
	SELECT ENAME,HIREDATE,DATENAME(WW,HIREDATE) FROM Emp
	SELECT ENAME,HIREDATE,+'WEEK-'+DATENAME(WW,HIREDATE) FROM Emp

-- DATEDIFF	(IT IS USED TO FIND THE DIFFERENCE B/W TWO DATES)
	SELECT ENAME,HIREDATE,DATEDIFF(YYYY,HIREDATE,GETDATE()) AS YEARS FROM Emp
	SELECT ENAME,HIREDATE,DATEDIFF(MM,HIREDATE,GETDATE()) AS MONTHS FROM Emp
	SELECT ENAME,HIREDATE,DATEDIFF(DD,HIREDATE,GETDATE()) AS DAYS FROM Emp

-- DATEADD (IT IS USED TO ADD / SUB THE DATES FROM THE ANY ONE OF THE DATE)
	SELECT DATEADD(DD,-2,GETDATE())
	SELECT ENAME,HIREDATE,DATEADD(DD,30,HIREDATE) AS ADDD FROM EMP
	SELECT ENAME,HIREDATE,DATEADD(MM,02,HIREDATE) AS ADDD FROM EMP
	SELECT ENAME,HIREDATE,DATEADD(YYYY,1,HIREDATE) AS ADDD FROM EMP



						-- CONVERSION FUNCTIONS

-- THESE FUNCTIONS ARE USED TO CONVERT ONE TYPE OF DATA INTO OTHER TYPE OF DATA
	-- A) CAST() --> CONVERTS A VALUE OF ANY TYPE INTO SPECIFIED DATA TYPE
	-- B) CONVERT() --> IT IS ALSO USED TO CONVERT ONE DATA TYPE TO ANOTHER DATA TYPE

-- CAST()
	SELECT CAST(12.3 AS INT)	-- O/P=12
	SELECT CAST('123' as int)	-- o/p=123
	SELECT CAST(GETDATE() AS varchar)	-- O/P=JULY 23 2021
	SELECT CAST(123 AS VARCHAR)	-- O/P=123

-- CONVERT()
	SELECT CONVERT(INT,12.3)	--O/P=12
	SELECT CONVERT(varchar,123)
	SELECT CONVERT(varchar,GETDATE())












	
