
							-- GROUP BY CLAUSE--

-- WRITE A QUERY TO GET DNO WISE MAX SALARY FROM EMP TABLE

SELECT DNO,MAX(ESALARY) AS MAXSAL FROM EMP GROUP BY DNO

-- WRITE A QUERY TO GET DNO WISE MIN SALARY FROM EMP TABLE

SELECT DNO,MIN(ESALARY) AS MINSAL FROM EMP GROUP BY DNO

-- WRITE A QUERY TO GET DNO WISE SUM OF SALARY FROM EMP TABLE

SELECT DNO,SUM(ESALARY) AS SUMOFSAL FROM EMP GROUP BY DNO

-- WRITE A QUERY TO GET JOB WISE MAX SALARY FROM EMP TABLE

SELECT JOB,MAX(ESALARY) AS MAXSAL FROM EMP GROUP BY JOB

-- WRITE A QUERY TO GET DNO WISE COUNT OF EMPS FROM EMP TABLE

SELECT DNO,COUNT(*) AS DNOCOUNT FROM EMP GROUP BY DNO

-- WRITE A QUERY TO GET JOB WISE COUNT OF EMPS FROM EMP TABLE

SELECT JOB,COUNT(*) AS COUNTOFJOB FROM EMP GROUP BY JOB

-- WRITE A QUERY TO GET DNO WISE SUM OF SALARY AND COUNT OF EMPS FROM EMP TABLE

SELECT DNO,SUM(ESALARY) AS TOTALSALARY,COUNT(*) AS TOTALEMP FROM EMP GROUP BY DNO


							-- HAVING CLAUSE--

-- WRITE A QUERY TO GET THE DNO WISE MAX SALARY WHERE DNO WISE MAX SALARY > 40000
SELECT DNO,MAX(ESALARY) AS MAXSAL FROM EMP GROUP BY  DNO HAVING MAX(ESALARY)>40000

-- WRITE A QUERY TO GET THE DNO WISE MIN SALARY WHERE DNO WISE MIN SALARY > 10000
SELECT DNO,MIN(ESALARY) AS MAXSAL FROM EMP GROUP BY  DNO HAVING MIN(ESALARY)>10000

-- WRITE A QUERY TO GET THE DNO WISE COUNT OF EMP WHERE COUNT OF EMP > 3
SELECT DNO,COUNT(*) AS COUNTOFDNO FROM EMP GROUP BY  DNO HAVING COUNT(*)>3

						-- ORDER BY CLAUSE--

SELECT * FROM EMP ORDER BY ESALARY -- BY DEFAULT IT IS IN ASCE ORDER

SELECT * FROM EMP ORDER BY ESALARY DESC -- THE O/P WILL BE IN DESC ORDER

						-- DISTINCT CLAUSE --

-- IT WILL GIVES THE DISTINCT (UNIQUE) VALUES IN A COLUMN
-- IT WILL REMOVE THE DUPLICATE VALUES UNDER THE COLUMN

SELECT DISTINCT(DNO) FROM EMP -- GIVES DISTINCT VALUES IN COLUMN

SELECT COUNT(DISTINCT DNO) FROM EMP -- COUNTS THE NO.OF DISTINCT VALUES IN A COLUMN

							-- WITH ROLLUP CLAUSE --

-- IT IS USED TO FIND SUB AND GRAND TOTAL OF A SINGLE COLUMN.

SELECT DNO,SUM(ESALARY) AS SUMSALARY FROM EMP GROUP BY DNO WITH ROLLUP

SELECT DNO,MAX(ESALARY) AS MAXSALARY FROM EMP GROUP BY DNO WITH ROLLUP

SELECT JOB,COUNT(*) AS TOTALJOBS FROM EMP GROUP BY JOB WITH ROLLUP

SELECT DNO,COUNT(*) AS TOTALJOBS FROM EMP GROUP BY DNO WITH ROLLUP

SELECT JOB,DNO,COUNT(*) AS TOTALJOBS FROM EMP GROUP BY JOB,DNO WITH ROLLUP -- WRONG O/P BECAUSE WITH ROLLUP WILL WORK ON SINGLE SINGLE COLUMN ONLY

							-- CUBE CLAUSE --

-- IT IS USED TO FIND SUB AND GRAND TOTAL OF GRAND TOTAL OF A MULTIPLE COLUMN.

SELECT JOB,DNO,COUNT(*) AS TOTALJOBS FROM EMP GROUP BY CUBE(DNO,JOB)



