
						-- SELECT TOP CLAUSE

SELECT * FROM EMP

SELECT TOP 2 * FROM EMP  -- SELECT TOP 2 BASE ON THE 1st COLUMN IN THE TABLE (ie. ENO) --> DEFAULT

SELECT TOP 2 * FROM EMP ORDER BY ESALARY DESC  -- SELECT TOP 2 BASED ON THE SALARY COLUMN
---------------------------------------------------------------------------------------

SELECT TOP 2 * FROM EMP WHERE DNO=20  --SELECT TOP 2 IN DNO=10 BASED ON *(ENO) -->DEFAULT

SELECT TOP 2 * FROM EMP WHERE DNO=20 ORDER BY ESALARY DESC -- SELECT TOP 2 IN DNO=10 BASED ON THE *(SALARY COLUMN)

------------------------------------------------------------------------------------------

/*FETCH
	FETCH IS USED TO SELECT THE ALTERNATE ROWS
	1)ORDER BY IS **(MANDATORY)   */

SELECT * FROM EMP ORDER BY ESALARY DESC OFFSET 2 ROWS -- IT WILL FETCH ALL ROWS EXCEPT (TOP 2)

SELECT * FROM EMP ORDER BY ESALARY DESC OFFSET 2 ROWS FETCH NEXT 1 ROW ONLY -- IT WILL FETCH 3 ROW ONLY

------------------------------------------------------------------------

SELECT * FROM EMP WHERE ENUM%2=0 -- TO GET THE EVEN NUMBER OF ROWS

SELECT * FROM EMP WHERE ENUM%2=1 -- TO GET THE ODD NUMBER OF ROWS
