CREATE DATABASE RANKING
USE RANKING
DROP TABLE RANKING
CREATE TABLE RANKING(ENO INT,ENAME VARCHAR(10),SALARY MONEY,DNO INT)

INSERT INTO RANKING VALUES(10,'SUNIL',10000,10)
INSERT INTO RANKING VALUES(11,'SRI',20000,20)
INSERT INTO RANKING VALUES(12,'WARNER',12000,30)
INSERT INTO RANKING VALUES(13,'SMITH',12000,20)
INSERT INTO RANKING VALUES(14,'SHEWAGE',12000,30)
INSERT INTO RANKING VALUES(15,'PATAN',19000,10)
INSERT INTO RANKING VALUES(16,'YUV',19000,20)
INSERT INTO RANKING VALUES(17,'PANDAY',21000,30)
INSERT INTO RANKING(ENO,ENAME,DNO) VALUES(18,'VVSL',30)

SELECT * FROM RANKING 

/* RANKING FUNCTIONS  --> TO ASSIGN THE RANK EACH ROW WISE AND GROUP OF ROWS WISE
		I) ROW_NUMBER()
		2) RANK()
		3) DENSE RANK()

	TO PERFORM RANKING FUNCTION *(ORDER BY CLAUSE) IS MANDATORY

	ORDER BY-->MANDATORY CLAUSE
	PARTITION BY--> OPTIONAL ON GROUP OF ROWS */

							--ROW_NUMBER()--
-- IT GIVES UNIQUE RANKINGS FOR EACH AND EVERY ROW IN A TABLE
SELECT ENAME,SALARY,ROW_NUMBER() OVER(ORDER BY SALARY DESC) AS RANKS FROM RANKING 
-- IF SAME SALARY REPEATING 2 TIMES IT GIVES CONTINOUS RANKING   (PROBLEM)

				--RANK()

--DUPLICATES RANKS ARE ALLOWED,GAPS ARE CREATED
SELECT ENAME,SALARY,RANK() OVER(ORDER BY SALARY DESC) AS RANKS FROM RANKING

				-- DENSE_RANK()

	-- WITHOUT GAPS CONTINOUS RANKS ARE GENERATED

SELECT ENAME,SALARY,DENSE_RANK() OVER(ORDER BY SALARY DESC) AS RANKS FROM RANKING

				-- PARTITION BY
	-- IT IS USED TO GET THE RANKS BASED ON GROUP OF ROWS

SELECT ENAME,DNO,SALARY,DENSE_RANK() OVER(PARTITION BY DNO ORDER BY SALARY DESC) AS RANKS FROM RANKING

------------------------------------------------------------------------------------------------


SELECT ENAME,SALARY,ROW_NUMBER() OVER(ORDER BY SALARY DESC) AS RANKS FROM RANKING

SELECT ENAME,SALARY,RANK() OVER(ORDER BY SALARY DESC) AS RANKS FROM RANKING

SELECT ENAME,SALARY,DENSE_RANK() OVER(ORDER BY SALARY DESC) AS RANKS FROM RANKING

SELECT ENAME,DNO,SALARY,DENSE_RANK() OVER(PARTITION BY DNO ORDER BY SALARY DESC) AS RANKS FROM RANKING

