DROP DATABASE CONSTRAINTS -- DROP DATABASE IF EXISTS

CREATE DATABASE CONSTRAINTS -- CREATE DATABASE
USE CONSTRAINTS -- CONNECTING TO THE DATABASE

DROP TABLE EMP -- DROP TABLE IF EXISTS

				-- DOMAIN --

-- CHECK,NOT NULL,DEFAULT CONSTRAINTS

CREATE TABLE EMP(EID INT,ENAME VARCHAR(10) NOT NULL,
SALARY MONEY CHECK(SALARY>10000),ADDRESS VARCHAR(10) DEFAULT'KP')

INSERT INTO EMP VALUES(1,'A',12000,'AMP')
INSERT INTO EMP VALUES(2,'B',15000,'SRN')
INSERT INTO EMP VALUES(3,'C',9000,'ERG') -- NOT ALLOWED ERROR

-- CHECK NOT NULL CONSTRAINT
INSERT INTO EMP (EID,SALARY,ADDRESS) VALUES(5,16000,'KOTI') -- NOT ALLOWED BECAUSE ENAME COLUMN CONTAINS A CONSTRAINT CALLED "NOTNULL"

SELECT * FROM EMP

-- CHECKING THE "CHECK" CONSTRAINT
INSERT INTO EMP VALUES(3,'C',9000,'ERG') -- NOT ALLOWED ERROR

-- CHECK DEFAULT CONSTRAINT
INSERT  INTO  EMP (EID,ENAME,SALARY)  VALUES  (4,'D',16000) -- HERE IT WILL TAKE DEFAULT ADDRESS AS THE ADDRESS

SELECT * FROM EMP

CREATE TABLE EMPLOYEES(EID INT IDENTITY(1,1),ENAME VARCHAR(20))

INSERT INTO EMPLOYEES VALUES('A'),('B'),('C')

SELECT * FROM EMPLOYEES
---------------------------------------------------------------------------
			-- ENTITY --

-- PRIMARY KEY (ONLY ONE P.K FOR ONE TABLE)
-- NO DUPLICATE, NO NULL VALUES

CREATE TABLE EMP1(EID INT PRIMARY KEY,ENAME VARCHAR(10))
INSERT INTO EMP1 VALUES(1,'AA')
INSERT INTO EMP1 VALUES(2,'BB')
INSERT INTO EMP1 VALUES(1,'CC') -- NOT ALLOWED

				-- UNIQUE --
-- NO DUPLICATES
-- ALLOWS ONE NULL VALUE
CREATE TABLE EMP2(EID INT UNIQUE,ENAME VARCHAR(10))
INSERT INTO EMP2 VALUES(1,'AA')
INSERT INTO EMP2 VALUES(2,'BB')

SELECT * FROM EMP2

INSERT INTO EMP2(ENAME) VALUES('CC') -- ALLOWS ONE NULL VALUE
INSERT INTO EMP2(ENAME) VALUES('DD') -- ERROR SECOND NULL VALUE NOT ALLOWED

				-- COMPOSITE KEY
-- HOW TO APPLY PRIMARY KEY FOR TWO COLUMNS
CREATE TABLE EMP3(EID INT,ENAME VARCHAR(10),PRIMARY KEY(EID,ENAME))

INSERT INTO EMP3 VALUES (1,'WARNER'),(2,'SMITH') -- ALLOWS
INSERT INTO EMP3 VALUES (1,'SCOOT')  -- ALLOWS
INSERT INTO EMP3 VALUES (2,'STARCH') -- ALLOWS
INSERT INTO EMP3 VALUES (1,'WARNER') -- NOT ALLOWED

INSERT INTO EMP3 VALUES (1,NULL) -- NOT ALLOWED



SELECT * FROM EMP3

sp_help EMP3