DROP DATABASE CONSTRAINTS -- DROP DATABASE IF EXISTS

CREATE DATABASE CONSTRAINTS -- CREATE DATABASE
USE CONSTRAINTS -- CONNECTING TO THE DATABASE

DROP TABLE EMP -- DROP TABLE IF EXISTS

				-- DOMAIN --

-- CHECK,NOT NULL,DEFAULT CONSTRAINTS

CREATE TABLE EMP(EID INT,ENAME VARCHAR(10) NOT NULL,
SALARY MONEY CHECK(SALARY>10000),ADDRESS VARCHAR(10) DEFAULT'KP')

INSERT INTO EMP VALUES(1,'A',12000,'AMP')
INSERT INTO EMP VALUES(2,'B',15000,'SRN')
INSERT INTO EMP VALUES(3,'C',9000,'ERG') -- NOT ALLOWED ERROR

-- CHECK NOT NULL CONSTRAINT
INSERT INTO EMP (EID,SALARY,ADDRESS) VALUES(5,16000,'KOTI') -- NOT ALLOWED BECAUSE ENAME COLUMN CONTAINS A CONSTRAINT CALLED "NOTNULL"

SELECT * FROM EMP

-- CHECKING THE "CHECK" CONSTRAINT
INSERT INTO EMP VALUES(3,'C',9000,'ERG') -- NOT ALLOWED ERROR

-- CHECK DEFAULT CONSTRAINT
INSERT  INTO  EMP (EID,ENAME,SALARY)  VALUES  (4,'D',16000) -- HERE IT WILL TAKE DEFAULT ADDRESS AS THE ADDRESS

SELECT * FROM EMP

CREATE TABLE EMPLOYEES(EID INT IDENTITY(1,1),ENAME VARCHAR(20))

INSERT INTO EMPLOYEES VALUES('A'),('B'),('C')

SELECT * FROM EMPLOYEES
---------------------------------------------------------------------------
			-- ENTITY --

-- PRIMARY KEY (ONLY ONE P.K FOR ONE TABLE)
-- NO DUPLICATE, NO NULL VALUES

CREATE TABLE EMP1(EID INT PRIMARY KEY,ENAME VARCHAR(10))
INSERT INTO EMP1 VALUES(1,'AA')
INSERT INTO EMP1 VALUES(2,'BB')
INSERT INTO EMP1 VALUES(1,'CC') -- NOT ALLOWED

				-- UNIQUE --
-- NO DUPLICATES
-- ALLOWS ONE NULL VALUE
CREATE TABLE EMP2(EID INT UNIQUE,ENAME VARCHAR(10))
INSERT INTO EMP2 VALUES(1,'AA')
INSERT INTO EMP2 VALUES(2,'BB')

SELECT * FROM EMP2

INSERT INTO EMP2(ENAME) VALUES('CC') -- ALLOWS ONE NULL VALUE
INSERT INTO EMP2(ENAME) VALUES('DD') -- ERROR SECOND NULL VALUE NOT ALLOWED

				-- COMPOSITE KEY
-- HOW TO APPLY PRIMARY KEY FOR TWO COLUMNS
CREATE TABLE EMP3(EID INT,ENAME VARCHAR(10),PRIMARY KEY(EID,ENAME))

INSERT INTO EMP3 VALUES (1,'WARNER'),(2,'SMITH') -- ALLOWS
INSERT INTO EMP3 VALUES (1,'SCOOT')  -- ALLOWS
INSERT INTO EMP3 VALUES (2,'STARCH') -- ALLOWS
INSERT INTO EMP3 VALUES (1,'WARNER') -- NOT ALLOWED

INSERT INTO EMP3 VALUES (1,NULL) -- NOT ALLOWED



SELECT * FROM EMP3

sp_help EMP3

--------------------------------------------------------------------------
		-- RELATIONSHIPS B/W THE TABLES

/* TO MAKE THE RELATIONSHIP B/W THE TWO TABLES WE NEED TO MAKE USE OF
	TWO CONSTRAINTS "PRIMARY KEY" AND "FORGIGN KEY" */
CREATE TABLE PARENT(DNO INT PRIMARY KEY,DNAME VARCHAR(10))
INSERT INTO PARENT VALUES(10,'SALES')
INSERT INTO PARENT VALUES(20,'ADMIN')
INSERT INTO PARENT VALUES(30,'DEV')

SELECT * FROM PARENT

CREATE TABLE CHILD(EID INT,ENAME VARCHAR(10),SALARY MONEY,
DNO INT FOREIGN KEY REFERENCES PARENT(DNO))

INSERT INTO CHILD VALUES(100,'AA',10000,10) -- ALLOWS
INSERT INTO CHILD VALUES(101,'BB',20000,20) -- ALLOWS
INSERT INTO CHILD VALUES(103,'CC',15000,30) -- ALLOWS

INSERT INTO CHILD VALUES(104,'DD',12000,40) -- NOT ALLOWED

-- FOURTH RECORD IS NOT ALLOWD BECAUSE DNO=40 DOES NOT EXISTS IN THE PARENT TABLE

SELECT * FROM CHILD

		-- UPDATE --
UPDATE PARENT SET DNO=1 WHERE DNO=10 -- NOT ALLOWED

		-- DELETE RULE
DELETE FROM PARENT WHERE DNO=10 -- NOT ALLOWED

-- UPDATE, DELETE CAN BE DONE BY USING CASCADE RULES IN THE CHILD TABLE
----------------------------------------------------------------------------
			-- ON DELETE, ON UPDATE CASCADE

CREATE TABLE PARENT1(DNO INT PRIMARY KEY,DNAME VARCHAR(10))
INSERT INTO PARENT1 VALUES(10,'SALES')
INSERT INTO PARENT1 VALUES(20,'ADMIN')
INSERT INTO PARENT1 VALUES(30,'DEV')

SELECT * FROM PARENT1

CREATE TABLE CHILD1(EID INT,ENAME VARCHAR(10),
SALARY MONEY,DNO INT FOREIGN KEY REFERENCES PARENT1(DNO)
ON DELETE CASCADE ON UPDATE CASCADE)
INSERT INTO CHILD1 VALUES(100,'AA',10000,10) -- ALLOWS
INSERT INTO CHILD1 VALUES(101,'BB',20000,20) -- ALLOWS
INSERT INTO CHILD1 VALUES(103,'CC',15000,30) -- ALLOWS

SELECT * FROM CHILD1

		-- INSERT RULE --
INSERT INTO CHILD1 VALUES(104,'DD',12000,40) -- NOT ALLOWED

		-- UPDATE RULE --
UPDATE PARENT1 SET DNO=1 WHERE DNO=10 -- ALLOWED

SELECT * FROM PARENT1

		-- DELETE RULE --
DELETE FROM PARENT1 WHERE DNO=1 -- ALLOWED
-------------------------------------------------------------

			-- SELF REFFERENCE KEY --

CREATE TABLE EMP6(EID INT PRIMARY KEY,ENAME VARCHAR(10),
MGRID INT FOREIGN KEY REFERENCES EMP6(EID))

INSERT INTO EMP6 VALUES(1001,'AA',1001) -- ALLOWES
INSERT INTO EMP6 VALUES(1002,'BB',1001) -- ALLOWES
INSERT INTO EMP6 VALUES(1003,'CC',1002) -- ALLOWES

SELECT * FROM EMP6

INSERT INTO EMP6 VALUES(1004,'AA',1006) -- NOT ALLOWED, BECAUSE THEIR IS NO EMP WITH ENO=1006

-- ADDING CONSTRAINT TO AN EXISTING TABLE

CREATE TABLE EMP9(EID INT NOT NULL,ENAME VARCHAR(10))

ALTER TABLE EMP9 ADD CONSTRAINT PK PRIMARY KEY (EID)

ALTER TABLE EMP9 ADD CONSTRAINT FK FOREIGN KEY (DNO) REFERENCES DEPT(DNO)

-- DROP CONSTRAINTS

ALTER TABLE EMP9 DROP CONSTRAINT PK

