CREATE DATABASE SUBQUERIES
USE SUBQUERIES

CREATE TABLE DEPARTMENT(DNO INT PRIMARY KEY,DNAME VARCHAR(20))

INSERT INTO DEPARTMENT VALUES(10,'HR')
INSERT INTO DEPARTMENT VALUES(20,'ADMIN')
INSERT INTO DEPARTMENT VALUES(30,'SALES')
INSERT INTO DEPARTMENT VALUES(40,'DEV')
INSERT INTO DEPARTMENT VALUES(50,'TESTING')

DROP TABLE EMPLOYEES

CREATE TABLE EMPLOYEES(ENUM INT UNIQUE,ENAME VARCHAR(20) NOT NULL,JOB VARCHAR(20) NOT NULL,
					HIREDATE DATE,ESALARY INT,DNO INT FOREIGN KEY REFERENCES DEPARTMENT(DNO))

INSERT INTO EMPLOYEES VALUES(101,'SUNIL','TRAINE','2020-02-12',50000,10)
INSERT INTO EMPLOYEES VALUES(102,'SRI','DEV','2020-02-12',20000,10)
INSERT INTO EMPLOYEES VALUES(103,'SHEWAG','PRESIDENT','2005-02-12',60000,30)
INSERT INTO EMPLOYEES VALUES(104,'KOHLI','DEV','2020-03-12',40000,20)
INSERT INTO EMPLOYEES VALUES(105,'WARNER','SLAESMAN','2021-02-12',25000,20)
INSERT INTO EMPLOYEES VALUES(106,'SMITH','CLERK','2021-10-12',35000,20)
INSERT INTO EMPLOYEES VALUES(107,'VENKY','ANALIYST','2021-02-12',25000,30)
INSERT INTO EMPLOYEES VALUES(108,'STARC','SLAESMAN','2021-02-12',25000,10)
INSERT INTO EMPLOYEES VALUES(109,'FINCH','CLERK','2021-02-12',12000,10)
INSERT INTO EMPLOYEES VALUES(110,'PANDYA','ANALYTS','2000-02-12',25000,30)
INSERT INTO EMPLOYEES VALUES(111,'MAXWELL','CLERK','2000-02-12',10000,10)
INSERT INTO EMPLOYEES VALUES(112,'VVSL','CLERK','2000-02-12',22000,20)
INSERT INTO EMPLOYEES VALUES(113,'ABD','CLERK','2000-02-12',22000,30)


SELECT * FROM EMPLOYEES



SELECT * FROM EMPLOYEES
SELECT * FROM DEPARTMENT

/* NON-CORRELATED SUB QUERY
	1)SINGLE ROW SUB QUERY */

--1)WRITE A QUERY TO GET MAX SAL EMP DETAILS?
	SELECT * FROM EMPLOYEES WHERE ESALARY=(SELECT MAX(ESALARY) FROM EMPLOYEES)

--2)WRITE A QUERY TO GET EMP DETAILS WHICH EMP SAL ABOVE AVG SAL OF DEPT NO 10?
	SELECT * FROM EMPLOYEES WHERE ESALARY>(SELECT AVG(ESALARY) FROM EMPLOYEES WHERE DNO=10)

--3)WRITE A QUERY TO GET EMP DETAILS WHICH EMP SAL GREATERTHAN OR EQUAL TO MAX SAL OF DEPT NO 10?
	SELECT * FROM EMPLOYEES WHERE ESALARY>=(SELECT MAX(ESALARY) FROM EMPLOYEES WHERE DNO=10)

--4)WRITE A QUERY TO GET EMP DETAILS WHICH EMP SAL BELOW AVG SAL OF DEPT NO 10?
	SELECT * FROM EMPLOYEES WHERE ESALARY<(SELECT AVG(ESALARY) FROM EMPLOYEES WHERE DNO=10)

--5)WRITE A QUERY TO GET DNO=10 EMP DETAILS WHICH EMP SAL BELOW AVG SAL OF DEPT NO 10?
	SELECT * FROM EMPLOYEES WHERE ESALARY<(SELECT AVG(ESALARY) FROM EMPLOYEES WHERE DNO=10) AND DNO=10

--6)WRITE A QUERY TO GET EMP DETAILS WHICH EMP SAL LESSTHAN OR EQUAL TO MAX SAL OF DEPT NO 10?
	SELECT * FROM EMPLOYEES WHERE ESALARY<=(SELECT MAX(ESALARY) FROM EMPLOYEES WHERE DNO=10)

--7)WRITE A QUERY TO GET EMP DETAILS WHICH EMP NOT WORKING IN 'SMITH' EMP DNO?
	SELECT * FROM EMPLOYEES WHERE DNO!=(SELECT DNO FROM EMPLOYEES WHERE ENAME='SMITH')

--8) WRITE A QUERY TO GET EMP DETAILS WHICH EMPS WORKING IN 'HR' DNO
	SELECT * FROM EMPLOYEES WHERE DNO=(SELECT DNO FROM DEPARTMENT WHERE DNAME='HR')

--9) WRITE A QUERY TO GET EMP DETAILS WHICH EMPS NOT WORKING IN 'HR' DNO
	SELECT * FROM EMPLOYEES WHERE DNO!=(SELECT DNO FROM DEPARTMENT WHERE DNAME='HR')

				-- MULTI-ROW SUB QUERY --
				
			-- IN OPERATOR


--1) WRITE A QUERY TO GET EMP DETAILS WHICH EMP SAL IS MATCH WITH DNO=20 EMP SAL
	SELECT * FROM EMPLOYEES WHERE ESALARY IN(SELECT ESALARY FROM EMPLOYEES WHERE DNO=20)

--2) WRITE A QUERY TO GET EMP DETAILS WHICH EMP ARE WORKING IN 'HR' OR 'SALES' DNAME
	SELECT ENUM,ENAME,JOB,ESALARY,DNO FROM EMPLOYEES WHERE DNO IN(SELECT DNO FROM DEPARTMENT WHERE DNAME='HR'OR DNAME='SALES')

--3) WRITE A QUERY TO GET EMP DETAILS WHICH EMP SAL IS NOT MATCH WITH DNO=20 EMP SAL
	SELECT * FROM EMPLOYEES WHERE ESALARY NOT IN(SELECT ESALARY FROM EMPLOYEES WHERE DNO=20)


			-- ANY OPERATOR --	(OR OPERATOR)

--1)WRITE A QUERY TO GET EMP DETAILS WHICH EMP SAL IS GREATER THAN "ANY" ONE OF DNO=20 SAL
	SELECT * FROM EMPLOYEES WHERE ESALARY>ANY(SELECT ESALARY FROM EMPLOYEES WHERE DNO=20)

--2)WRITE A QUERY TO GET EMP DETAILS WHICH EMP SAL IS GREATER THAN OR EQUAL TO "ANY" ONE OF DNO=20 SAL
	SELECT * FROM EMPLOYEES WHERE ESALARY>=ANY(SELECT ESALARY FROM EMPLOYEES WHERE DNO=20)

--3)WRITE A QUERY TO GET EMP DETAILS WHICH EMP SAL IS LESS THAN "ANY" ONE OF DNO=20 SAL
	SELECT * FROM EMPLOYEES WHERE ESALARY<ANY(SELECT ESALARY FROM EMPLOYEES WHERE DNO=20)

--4)WRITE A QUERY TO GET EMP DETAILS WHICH EMP SAL IS LESS THAN OR EQUAL "ANY" ONE OF DNO=20 SAL
	SELECT * FROM EMPLOYEES WHERE ESALARY<=ANY(SELECT ESALARY FROM EMPLOYEES WHERE DNO=20)


			-- ALL OPERATOR -- (AND OPERATOR)

--1)WRITE A QUERY TO GET EMP DETAILS WHICH EMP SAL IS GREATER THAN "ALL" THE SALARIES OF DNO=20 
	SELECT * FROM EMPLOYEES WHERE ESALARY>ALL(SELECT ESALARY FROM EMPLOYEES WHERE DNO=20)

--2)WRITE A QUERY TO GET EMP DETAILS WHICH EMP SAL IS GREATER THAN OR EQUAL TO "ALL" THE SALARIES OF DNO=20 
	SELECT * FROM EMPLOYEES WHERE ESALARY>=ALL(SELECT ESALARY FROM EMPLOYEES WHERE DNO=20)

--3)WRITE A QUERY TO GET EMP DETAILS WHICH EMP SAL IS LESS THAN "ALL" SAL OF DNO=20
	SELECT * FROM EMPLOYEES WHERE ESALARY<ALL(SELECT ESALARY FROM EMPLOYEES WHERE DNO=20)
	SELECT ESALARY FROM EMPLOYEES WHERE DNO=20

--4)WRITE A QUERY TO GET EMP DETAILS WHICH EMP SAL IS LESS THAN OR EQUAL TO "ALL" SAL OF DNO=20
	SELECT * FROM EMPLOYEES WHERE ESALARY<=ALL(SELECT ESALARY FROM EMPLOYEES WHERE DNO=20)