DROP DATABASE SUBLANGUAGES

CREATE DATABASE SUBLANGUAGES
USE SUBLANGUAGES

CREATE TABLE EMP(EID INT,ENAME VARCHAR(10),ESALARY INT,DNO INT)

SELECT * FROM EMP


 SP_HELP EMP    -- USED TO SEE THE STRUCTURE OF A TABLE
-----------------------------------------------------------------

 			--DDL	(DATA DEFINATION LANGUAGE)
			
	-- ALTER TABLE

--1) CHANGE THE DATATYPE/SIZE OF A COLUMN

ALTER TABLE EMP ALTER COLUMN ESALARY BIGINT	-- CHANGE THE DATATYPE OF THE COLUMN

ALTER TABLE EMP ALTER COLUMN ENAME VARCHAR(50)	-- CHANGED THE SIZE OF THE CLOUMN

			-- ADD COLUMNS
-- ADDING THE NEW COLUMN TO AN EXISTING TABLE

ALTER TABLE EMP ADD JOB VARCHAR(10)

			--DROP COLUMN

ALTER TABLE EMP DROP COLUMN JOB		-- HERE WE DROP THE SINGLE COLUMN IN A TABLE

DROP TABLE EMP		-- COMPLETE TABLE IS DROPED (NO ROLLBACH/UNDO)

DROP DATABASE SUBLANGUAGES		-- THE DATABASE IS DROPED

			-- TRUNCATE TABLE	
--(ALL ROWS ARE ELIMINATED) BUT THE STRUCTURE OF THE TABLE IS SAME

INSERT INTO EMP VALUES(1,'SUNIL',10000,10)
INSERT INTO EMP VALUES(2,'SRI',9000,20)

TRUNCATE TABLE EMP		-- ALL THE ROWS IN THE TABLE IS ELIMINATED (NO ROLLBACK/UNDO AGAIN)
