DROP DATABASE SUBLANGUAGES

CREATE DATABASE SUBLANGUAGES
USE SUBLANGUAGES

CREATE TABLE EMP(EID INT,ENAME VARCHAR(10),ESALARY INT,DNO INT)

SELECT * FROM EMP


 SP_HELP EMP    -- USED TO SEE THE STRUCTURE OF A TABLE
-----------------------------------------------------------------

 			--DDL	(DATA DEFINATION LANGUAGE)
			
	-- ALTER TABLE

--1) CHANGE THE DATATYPE/SIZE OF A COLUMN

ALTER TABLE EMP ALTER COLUMN ESALARY BIGINT	-- CHANGE THE DATATYPE OF THE COLUMN

ALTER TABLE EMP ALTER COLUMN ENAME VARCHAR(50)	-- CHANGED THE SIZE OF THE CLOUMN

			-- ADD COLUMNS
-- ADDING THE NEW COLUMN TO AN EXISTING TABLE

ALTER TABLE EMP ADD JOB VARCHAR(10)

			--DROP COLUMN

ALTER TABLE EMP DROP COLUMN JOB		-- HERE WE DROP THE SINGLE COLUMN IN A TABLE

DROP TABLE EMP		-- COMPLETE TABLE IS DROPED (NO ROLLBACH/UNDO)

DROP DATABASE SUBLANGUAGES		-- THE DATABASE IS DROPED

			-- TRUNCATE TABLE	
--(ALL ROWS ARE ELIMINATED) BUT THE STRUCTURE OF THE TABLE IS SAME

INSERT INTO EMP VALUES(1,'SUNIL',10000,10)
INSERT INTO EMP VALUES(2,'SRI',9000,20)

TRUNCATE TABLE EMP		-- ALL THE ROWS IN THE TABLE IS ELIMINATED (NO ROLLBACK/UNDO AGAIN)


------------------------------------------------------------------------------=
			--DML	(DATA MANIPULATION LANGUAGE)

CREATE TABLE EMPLOYEES(ENO INT,ENAME VARCHAR (10),JOB VARCHAR (10),ESALARY INT,DNO INT)

-- INSERT (USED TO INSERT THE RECORDS INTO THE TABLES )

INSERT INTO EMPLOYEES VALUES(1,'SUNIL','TRAINE',10000,10)
INSERT INTO EMPLOYEES VALUES(2,'SRI','DEV',9000,20)
INSERT INTO EMPLOYEES VALUES(3,'RAM','SALES',8000,30)
INSERT INTO EMPLOYEES VALUES(4,'WARNER','DEV',5000,10)
INSERT INTO EMPLOYEES VALUES(5,'ABD','SALES',8000,20)

--UPDATE	(USED TO UPDATE THE RECORDS)

UPDATE EMPLOYEES SET ESALARY=25000 -- IT WILL UPDATES ALL THE RECORDS IN THE ESALARY COLUMN WITH 25000
									-- IT IS NOT RECOMMENDED TO UPDATE ALL THE RECORDS IN A COLUMN WITH 25000

UPDATE EMPLOYEES SET ESALARY=15000 WHERE ENO=3 -- IT WILL UPDATES A PARTICULAR RECORD IN THE COLUMN

UPDATE EMPLOYEES SET DNO=10 WHERE ENAME='ABD'

UPDATE EMPLOYEES SET JOB='DEV',ESALARY=11000 WHERE ENAME='SMITH' -- UPDATING MULTIPLE RECORDS IN A ROW

UPDATE EMPLOYEES SET ENO=10,ENAME='AAA',JOB='DEV',
				ESALARY=11000,DNO=20 WHERE ENO=1 -- UPDATING ALL THE RECORDS IN A ROW

--DELETE	(USED TO DELETE THE RECORDS)

DELETE FROM EMPLOYEES  -- DELETES ALL THE RECORDS IN THE TABLES (ROLLBACK)

DELETE FROM EMPLOYEES WHERE ENO=3 -- DELETES PARTICULAR RECORD IN THE TABLE

DELETE FROM EMPLOYEES WHERE ENAME='ABD' -- DELETES PARTICULAR RECORD IN THE TABLE


SELECT * FROM EMPLOYEES
-------------------------------------------------------------------------------------

-- HOW TO INSERT THE DATA UNDER THE PARTICULAR COLUMN ONLY

INSERT INTO EMPLOYEES(ENO,ENAME)VALUES(1,'SUNIL')

-----------------------------------------------------------------------------------
			-- DRL	(DATA RETRIVAL LANGUAGE) SELECT

SELECT * FROM EMPLOYEES -- FETCHES ALL COLUMNS,RECORDS FROM THE TABLES

SELECT ENO,ENAME,ESALARY FROM EMPLOYEES -- FETCHES ONLY THE SELECTED COLUMNS FROM THE TABLE



-- DIFFERENT WAYS OF SELECTING THE DATA FROM THE DATABASE

SELECT * FROM EMPLOYEES									-- 1 PART NAMING 
SELECT * FROM [dbo].[EMPLOYEES]							-- 2 PART NAMING 
SELECT * FROM [SUBLANGUAGES].[dbo].[EMPLOYEES]			-- 3 PART NAMING  
-----------------------------------------------------------------------------------
	-- WHERE CLAUSE (******)

SELECT * FROM EMPLOYEES WHERE ENO=1	-- WHERE CONDITION
SELECT * FROM EMPLOYEES WHERE ENAME='SRI'	-- WHERE CONDITION

DROP TABLE EMPLOYEES





