

DROP TABLE PRODUCTS

CREATE TABLE PRODUCTS(PID INT,PRODUCT VARCHAR(10),UNITS INT,COST INT,SALES INT)

INSERT INTO PRODUCTS VALUES(1,'MOBILE',3,500,700)
INSERT INTO PRODUCTS VALUES(2,'LAPTOPS',4,300,650)
INSERT INTO PRODUCTS VALUES(3,'PC',2,200,350)

SELECT * FROM PRODUCTS

				-- ARITHMETIC OPERATORS
	-- ADDITION
	-- SUBTRACTION
	-- MULTIPLICATION
	-- DIVISION
	-- MODULES

-- WRITE A QUERY TO GET SUM OF COST+SALES

SELECT COST,SALES,ADDITION=COST+SALES FROM PRODUCTS	-- ADDITION OF TWO COLUMNS

-- WRITE A QUERY TO GET DIFFERENCE OF SALES-COST

SELECT COST,SALES,SUB=SALES-COST FROM PRODUCTS	-- SUB OF TWO NUMBERS

----- WRITE A QUERY TO GET MUL OF UNITS*COST

SELECT UNITS,COST,MUL=UNITS*COST FROM PRODUCTS	-- PRODUCT OF TWO NUMBERS

-- WRITE A QUERY TO GET SALES/COST

SELECT COST,SALES,DIV=SALES/COST FROM PRODUCTS	-- IT GIVES NO.OF TIMES IS DIVISIBLE

-- WRITE A QUERY TO GET SALES%COST

SELECT COST,SALES,MODULES=SALES%COST FROM PRODUCTS	-- IT GIVES THE REMAINDER

-- WRITE A QUERY TO GET TOTAL PROFITS FOR EACH PRODUCT

SELECT PRODUCT,((SALES-COST)*UNITS) AS PROFIT FROM PRODUCTS

				--COMPARISON OPERATORS
/*
	=		(EQUAL TO)
	<>,!=	(NOT-EQUAL TO)
	>		(GREATER THAN)
	<		(LESS THAN)
	>=		(GREATER THAN OR EQUAL TO)
	<=		(LESS THAN OR EQUAL TO)	*/

SELECT * FROM PRODUCTS

-- WRITE A QUERY TO GET ALL THE PRODUCT DETAILS WHERE PRODUCT='MOBILE'

SELECT * FROM PRODUCTS WHERE PRODUCT='MOBILE'

-- WRITE A QUERY TO GET THE PRODUCT DETAILS WHERE PRODUCT<>'MOBILE'

SELECT * FROM PRODUCTS WHERE PRODUCT<>'MOBILE'

SELECT * FROM PRODUCTS WHERE PRODUCT!='MOBILE'

-- WRITE A QUERY TO GET THE PRODUCT DETAILS WHERE COST>300

SELECT * FROM PRODUCTS WHERE COST>300

-- WRITE A QUERY TO GET THE PRODUCT DETAILS WHERE COST<300

SELECT * FROM PRODUCTS WHERE COST<300

-- WRITE A QUERY TO GET THE PRODUCT DETAILS WHERE COST>=300

SELECT * FROM PRODUCTS WHERE COST>=300

-- WRITE A QUERY TO GET THE PRODUCT DETAILS WHERE COST<=350

SELECT * FROM PRODUCTS WHERE COST<=300
