CREATE DATABASE OPERATORS

USE OPERATORS

DROP TABLE PRODUCTS

CREATE TABLE PRODUCTS(PID INT,PRODUCT VARCHAR(10),UNITS INT,COST INT,SALES INT)

INSERT INTO PRODUCTS VALUES(1,'MOBILE',3,500,700)
INSERT INTO PRODUCTS VALUES(2,'LAPTOPS',4,300,650)
INSERT INTO PRODUCTS VALUES(3,'PC',2,200,350)

SELECT * FROM PRODUCTS

				-- ARITHMETIC OPERATORS
	-- ADDITION
	-- SUBTRACTION
	-- MULTIPLICATION
	-- DIVISION
	-- MODULES

-- WRITE A QUERY TO GET SUM OF COST+SALES

SELECT COST,SALES,ADDITION=COST+SALES FROM PRODUCTS	-- ADDITION OF TWO COLUMNS

-- WRITE A QUERY TO GET DIFFERENCE OF SALES-COST

SELECT COST,SALES,SUB=SALES-COST FROM PRODUCTS	-- SUB OF TWO NUMBERS

-- WRITE A QUERY TO GET MUL OF UNITS*COST

SELECT UNITS,COST,MUL=UNITS*COST FROM PRODUCTS	-- PRODUCT OF TWO NUMBERS

-- WRITE A QUERY TO GET SALES/COST

SELECT COST,SALES,DIV=SALES/COST FROM PRODUCTS	-- IT GIVES NO.OF TIMES IS DIVISIBLE

-- WRITE A QUERY TO GET SALES%COST

SELECT COST,SALES,MODULES=SALES%COST FROM PRODUCTS	-- IT GIVES THE REMAINDER

-- WRITE A QUERY TO GET TOTAL PROFITS FOR EACH PRODUCT

SELECT PRODUCT,((SALES-COST)*UNITS) AS PROFIT FROM PRODUCTS

				--COMPARISON OPERATORS
/*
	=		(EQUAL TO)
	<>,!=	(NOT-EQUAL TO)
	>		(GREATER THAN)
	<		(LESS THAN)
	>=		(GREATER THAN OR EQUAL TO)
	<=		(LESS THAN OR EQUAL TO)	*/

SELECT * FROM PRODUCTS

-- WRITE A QUERY TO GET ALL THE PRODUCT DETAILS WHERE PRODUCT='MOBILE'

SELECT * FROM PRODUCTS WHERE PRODUCT='MOBILE'

-- WRITE A QUERY TO GET THE PRODUCT DETAILS WHERE PRODUCT<>'MOBILE'

SELECT * FROM PRODUCTS WHERE PRODUCT<>'MOBILE'

SELECT * FROM PRODUCTS WHERE PRODUCT!='MOBILE'

-- WRITE A QUERY TO GET THE PRODUCT DETAILS WHERE COST>300

SELECT * FROM PRODUCTS WHERE COST>300

-- WRITE A QUERY TO GET THE PRODUCT DETAILS WHERE COST<300

SELECT * FROM PRODUCTS WHERE COST<300

-- WRITE A QUERY TO GET THE PRODUCT DETAILS WHERE COST>=300

SELECT * FROM PRODUCTS WHERE COST>=300

-- WRITE A QUERY TO GET THE PRODUCT DETAILS WHERE COST<=350

SELECT * FROM PRODUCTS WHERE COST<=300

				-- LOGICAL OPERATORS
	-- AND
	-- OR
	-- NOT

create table EMP(EID INT,ENAME VARCHAR(10),JOB VARCHAR(10),DNO INT)
insert into EMP VALUES(101,'ADAMS','CLERK',10),
							(102,'MILLER','SALESMAN',20),
							(103,'SCOOT','DEV',30),
							(104,'PANDY','ADMIN',10)

-- WRITE A QUERY TO GET EMP DETAILS WHERE JOB='CLERK' AND DNO=10

SELECT * FROM EMP WHERE JOB='CLERK' AND DNO=10 --> TRUE

-- WRITE A QUERY TO GET EMP DETAILS WHERE JOB='SALES' AND DNO=10

SELECT * FROM EMP WHERE JOB='SALES' AND DNO=10 --> FALSE	

-- WRITE A QUERY TO GET EMP DETAILS WHERE JOB='CLERK' OR DNO=10

SELECT * FROM EMP WHERE JOB='CLERK' OR DNO=10

-- WRITE A QUERY TO GET EMP DETAILS WHERE JOB='HR' OR DNO=30

SELECT * FROM EMPLOYEES WHERE DNO=30 OR JOB='HR' -- TRUE (ONE CONDITION IS TRUE 2ND CONDITION IS FALSE)

-- WRITE A QUERY TO GET EMP DETAILS WHERE JOB='HR' OR DNO=40

SELECT * FROM EMPLOYEES WHERE DNO=40 OR JOB='HR' -- FALSE (BOTH THE CONDITIONS ARE FALSE)

-- WRITE A QUERY TO GET EMP DETAILS WHERE DNO NOT=10

SELECT * FROM EMP WHERE NOT DNO=10
------------------------------------------------------------------
			-- SET OPERATORS
	-- UNION --> ALL THE VALUES IN ALL THE ROWS HAS TO BE SAME THEN ONLY IT WILL REMOVES THE DUPLICATES
	-- UNION ALL
	-- INTERSECT
	-- EXCEPT

	/*RULES
	-------
	1.THE STRUCTURE OF THE TABLE SHOULD BE SAME **
	2.NO.OF COLUMNS IN THE TABLES SHOULD BE SAME **
	3.DATA TYPES OF THE COLUMNS IS ALSO SAME **
	4.ORDER OF THE COLUMNS IN BOTH THE TABLES SHOULD BE SAME **/

DROP TABLE EMP_HYD

create table EMP_HYD(EID INT,ENAME VARCHAR(10),ESALARY INT)
insert into EMP_HYD VALUES(101,'ADAMS',85000),
							(102,'MILLER',76000),
							(103,'SCOOT',45000),
							(104,'PANDY',46000)
SELECT * FROM EMP_HYD

DROP TABLE EMP_CHENNAI

create tablE EMP_CHENNAI(EID INT,ENAME VARCHAR(10),ESALARY INT)
insert into EMP_CHENNAI VALUES(101,'ADAMS',85000)
insert into EMP_CHENNAI VALUES(105,'warner',35000)
insert into EMP_CHENNAI VALUES(106,'finch',56000)

SELECT * FROM EMP_CHENNAI

-- UNION	(WITH OUT DUPLICATES)

SELECT * FROM EMP_HYD
UNION
SELECT * FROM EMP_CHENNAI

-- UNION ALL	(WITH DUPLICATES)
SELECT * FROM EMP_HYD
UNION ALL
SELECT * FROM EMP_CHENNAI

-- INTERSECT	(COMMON RECORDS IN BOTH THE TABLES)
SELECT * FROM EMP_HYD
INTERSECT
SELECT * FROM EMP_CHENNAI

-- EXCEPT	(NON-MATCHING RECORDS FROM LEFT SIDE TABLE)
SELECT * FROM EMP_HYD
EXCEPT
SELECT * FROM EMP_CHENNAI

-- UNION	(WITH OUT DUPLICATES)
-- UNION WITH SELECTED COLUMNS IN TABLE 1 AND TABLE 2
SELECT ENAME,ESALARY FROM EMP_HYD
UNION
SELECT ENAME,ESALARY FROM EMP_CHENNAI




