CREATE DATABASE SPECIALOPERATORS

USE SPECIALOPERATORS

CREATE TABLE EMPLOYEES(ENUM INT,ENAME VARCHAR(20),JOB VARCHAR(20),
HIREDATE DATE,ESALARY INT,DNO INT)
INSERT INTO EMPLOYEES VALUES(101,'SUNIL','TRAINE','2020-02-12',50000,10)
INSERT INTO EMPLOYEES VALUES(102,'SRI','DEV','2020-02-12',20000,10)
INSERT INTO EMPLOYEES VALUES(103,'SHEWAG','PRESIDENT','2005-02-12',60000,10)
INSERT INTO EMPLOYEES VALUES(104,'KOHLI','DEV','2020-03-12',40000,10)
INSERT INTO EMPLOYEES VALUES(105,'WARNER','SLAESMAN','2021-02-12',25000,20)
INSERT INTO EMPLOYEES VALUES(106,'SMITH','CLERK','2021-10-12',35000,20)
INSERT INTO EMPLOYEES VALUES(107,'VENKY','ANALYST','2021-02-12',25000,20)
INSERT INTO EMPLOYEES VALUES(108,'STARC','SLAESMAN','2021-02-12',25000,20)
INSERT INTO EMPLOYEES VALUES(109,'FINCH','CLERK','2021-02-12',12000,30)
INSERT INTO EMPLOYEES VALUES(110,'PANDYA','ANALYST','2000-02-12',25000,30)
INSERT INTO EMPLOYEES VALUES(111,'MAXWELL','CLERK','2000-02-12',10000,30)

				-- IN	(ANY ONE IS MATCHING IT WILL GIVE THE O/P)

-- IN OPERATOR IS EQUAL TO (OR)

--1) WRITE A QUERY TO GET EMP DETAILS WHERE EMPNO IN(101,105,108)
SELECT * FROM EMPLOYEES WHERE ENUM IN(101,105,108)

--1) WRITE A QUERY TO GET EMP DETAILS WHERE EMPNO NOT IN(101,105,108)
SELECT * FROM EMPLOYEES WHERE ENUM NOT IN(101,105,108)

--1) WRITE A QUERY TO GET EMP DETAILS WHERE job IN('CLERK''SALESMAN')
SELECT * FROM EMPLOYEES WHERE JOB IN('CLERK','SALESMAN')

			-- BETWEEN-AND	(RANGE OF VALUES)IN A CLOUMN

--1) WRITE A QUERY TO GET EMP DETAILS WHERE SAL B/W 20000 AND 30000
SELECT * FROM EMPLOYEES WHERE ESALARY BETWEEN 20000 AND 30000

--WRITE A QUERY TO GET THE EMP DETAILS WHERE HIREDATE B/W 01/01/2005 AND 12/10/2020 
SELECT * FROM EMPLOYEES WHERE HIREDATE BETWEEN '01/01/2005' AND '12/10/2020' -- MM/DD/YYYY

		-- NOT BETWEEN-AND	(RANGE OF VALUES)IN A CLOUMN

--1) WRITE A QUERY TO GET EMP DETAILS WHERE SAL NOT B/W 20000 AND 30000
SELECT * FROM EMPLOYEES WHERE ESALARY NOT BETWEEN 20000 AND 30000

		-- BETWEEN WITH IN 	(RANGE OF VALUES)IN A CLOUMN

--1) WRITE A QUERY TO GET EMP DETAILS WHERE SAL B/W 20000 AND 30000 AND EMPNO IN(102,108,110)
SELECT * FROM EMPLOYEES
WHERE 
ESALARY BETWEEN 20000 AND 30000 
AND  ENUM IN (102,108,122)

			--	LIKE	(WHERE CLAUSE IS MANDATORY)

--1) WRITE A QUERY TO GET EMP DETAILS WHOSE NAME STARTS WITH 'S'
SELECT * FROM EMPLOYEES WHERE ENAME LIKE'S%'

--2) WRITE A QUERY TO GET EMP DETAILS WHOSE NAME ENDS WITH 'H'
SELECT * FROM EMPLOYEES WHERE ENAME LIKE'%H'

--3) WRITE A QUERY TO GET EMP DETAILS WHOSE NAME HAS 'AR'
SELECT * FROM EMPLOYEES WHERE ENAME LIKE'%AR%'

--4) WRITE A QUERY TO GET EMP DETAILS WHOSE NAME HAS 'A' IN THE SECOND POSITION
SELECT * FROM EMPLOYEES WHERE ENAME LIKE'_A%'

--5) WRITE A QUERY TO GET EMP DETAILS WHOSE NAME STARTS WITH 'S' AND HAS ATLEAST TWO CHARACTERS
SELECT * FROM EMPLOYEES WHERE ENAME LIKE'S%_'

--6) WRITE A QUERY TO GET EMP DETAILS WHOSE NAME STARTS WITH 'S' AND HAS ATLEAST FOUR CHARACTERS
SELECT * FROM EMPLOYEES WHERE ENAME LIKE'S%___'

--7) WRITE A QUERY TO GET EMP DETAILS WHOSE NAME STARTS WITH 'S' AND ENDS WITH 'H'
SELECT * FROM EMPLOYEES WHERE ENAME LIKE'S%H'

				-- NULL VALUES
--	IS NULL (TO FIND OUT THE NULL VALUES IN A COLUMN)

UPDATE EMPLOYEES SET ESALARY=NULL WHERE ESALARY=25000

-- WRITE A QUERY TO GET THE EMP DETAILS WHERE WHOSE SALARY IS NULL FROM THE EMP TABLE
SELECT * FROM EMPLOYEES WHERE ESALARY IS NULL -- SELECTS ONLY THE RECORDS WHERE ESALARY IS NULL

-- WRITE A QUERY TO GET THE EMP DETAILS WHERE WHOSE SALARY IS NOT NULL FROM THE EMP TABLE
SELECT * FROM EMPLOYEES WHERE ESALARY IS NOT NULL -- SELECTS ONLY THE RECORDS WHERE ESALARY IS NOT NULL

-- WRITE A QUERY TO GET THE NULL VALUES FROM THE MULTIPLE COLUMNS FROM A TABLE
SELECT * FROM EMPLOYEES WHERE ESALARY IS NULL OR DNO IS NULL

