CREATE DATABASE OPERATORS
USE OPERATORS
CREATE TABLE PRODUCTS(PID INT, PNAME VARCHAR(20),QUANTITY INT,COST INT,SALES INT)
INSERT INTO PRODUCTS VALUES(1,'MOBILES',4,300,500)
INSERT INTO PRODUCTS VALUES(2,'LAPTOPS',5,500,600)
INSERT INTO PRODUCTS VALUES(3,'MOUSES',2,150,200)
SELECT * FROM PRODUCTS

-- ARITHMETIC OPERATORS
-- WRITE A QUERY TO GET ADD THE COST+SALES
SELECT PNAME AS PRODUCTNAME,COST,SALES,SALES+COST AS COMBINE FROM PRODUCTS
--WRITE A QUERY TO GET DIFFERENCE OF SALES-COST
SELECT PNAME,COST,SALES,SALES-COST AS PROFIT FROM PRODUCTS
--WRITE A QUERY TO GET MUL OF QUANTITY*COST
SELECT * FROM PRODUCTS
SELECT PNAME,QUANTITY,COST,QUANTITY*COST AS TOATALPRODUCT FROM PRODUCTS
-- WRITE A QUERY TO GET TOTAL PROFITS FOR EACH PRODUCT
SELECT * FROM PRODUCTS
SELECT PNAME, COST, SALES, (SALES-COST)*QUANTITY AS TOATALPROFIT FROM PRODUCTS
SELECT PNAME, COST, SALES, (SALES-COST)/QUANTITY AS TOATALPROFIT FROM PRODUCTS
-- WRITE A QUERY TO GET SALES/COST
SELECT PNAME,SALES,COST,SALES/COST AS TOTALAMOUNT FROM PRODUCTS
--WRITE A QUERY TO GET SALES%COST
SELECT * FROM PRODUCTS
--SALES PERCENTAGE
SELECT PNAME,SALES,COST,(SALES%COST)/100 AS MODULES FROM PRODUCTS